server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME:localhost}:${DB_PORT:5432}/${DB_NAME:community-manager}
    username: ${DB_USERNAME:user123}
    password: ${DB_PASSWORD:pass123}
  jpa:
    hibernate:
      ddl-auto: update
